on: workflow_call

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: print out example job
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 30m
          script: |
            source ~/.nvm/nvm.sh
            cd ~/audiofeedback-backend/
            docker compose down
            pm2 kill
            git pull
            docker compose up -d
            npm install
            npm run build
            pm2 start "npm run start:prod"
